blank_issues_enabled: false
contact_links:
  - name: Support ❔
    url: https://github.com/PtPrashantTripathi/2024_US_Election_Predictions/issues/
    about: I need support with 2024_US_Election_Predictions.
